name: gitu
base: core24
summary: A terminal user interface for Git. Inspired by Magit.
description: |
  Gitu aims to implement many of the core features of Magit over time.
  It should be familiar to any previous Magit users.

contact: https://github.com/mr-cal/gitu-snap/issues
issues:
  - https://github.com/mr-cal/gitu-snap/issues
  - https://github.com/altsem/gitu/issues
source-code:
  - https://github.com/altsem/gitu
  - https://github.com/mr-cal/gitu-snap
website: https://github.com/altsem/gitu

adopt-info: gitu
grade: stable
confinement: strict

apps:
  gitu:
    command: bin/gitu
    plugs:
      - home
      - removable-media

parts:
  gitu:
    plugin: rust
    source: https://github.com/altsem/gitu.git
    stage-packages:
      - git
    override-build: |
      craftctl set version="$(git describe --always --match 'v[0-9]*.[0-9]*.[0-9]*' --exclude '*[^v0-9.]*')"
      craftctl default
